/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.segundoproyecto.frontend;


import com.mycompany.segundoproyecto.carta.AdministradorCartas;
import com.mycompany.segundoproyecto.carta.CartaMonstruo;
import com.mycompany.segundoproyecto.carta.Elemento;
import java.io.IOException;

/**
 *
 * @author fer
 */
public class EditorDeCartas extends javax.swing.JFrame {

    /**
     * Creates new form EditorDeCartas
     */
    public EditorDeCartas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEditor = new javax.swing.JPanel();
        lblNombreCarta = new javax.swing.JLabel();
        txtNombreCarta = new javax.swing.JTextField();
        lblSubTipoCarta = new javax.swing.JLabel();
        boxSubTipoC = new javax.swing.JComboBox<>();
        lblPV = new javax.swing.JLabel();
        spinerPV = new javax.swing.JSpinner();
        lblFase = new javax.swing.JLabel();
        boxFase = new javax.swing.JComboBox<>();
        lblHabilidadesAtaque = new javax.swing.JLabel();
        boxHabilidad = new javax.swing.JComboBox<>();
        lblHabilidad = new javax.swing.JLabel();
        lblAtq = new javax.swing.JLabel();
        spinnerAtq = new javax.swing.JSpinner();
        lblAccion = new javax.swing.JLabel();
        spinnerAccion = new javax.swing.JSpinner();
        lblCostoRetirada = new javax.swing.JLabel();
        spinnerRetirada = new javax.swing.JSpinner();
        panelVentana = new javax.swing.JPanel();
        lblFaseVentana = new javax.swing.JLabel();
        lblNombreVentana = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTipoVentana = new javax.swing.JLabel();
        lblPvidaVentana = new javax.swing.JLabel();
        lblAtqVentana = new javax.swing.JLabel();
        lblEnergiaVentana = new javax.swing.JLabel();
        lblHabilidadVentana = new javax.swing.JLabel();
        lblCosteVentana = new javax.swing.JLabel();
        btnGuardarCartta = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelEditor.setBackground(new java.awt.Color(102, 102, 102));

        lblNombreCarta.setText("Nombre Carta");

        txtNombreCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCartaActionPerformed(evt);
            }
        });

        lblSubTipoCarta.setText("Sub Tipo");

        boxSubTipoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuego", "Agua", "Viento", "Tierra" }));

        lblPV.setText("Puntos de vida");

        lblFase.setText("Fase");

        boxFase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico", "Evolución Fase 1", "Evolución Fase 2", "Evolución Fase 3" }));

        lblHabilidadesAtaque.setText("Habilidades de Ataque");

        boxHabilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblHabilidad.setText("Habilidad");

        lblAtq.setText("Daño de Ataque");

        lblAccion.setText("Accion");

        lblCostoRetirada.setText("Costo de Retirada");

        panelVentana.setBackground(new java.awt.Color(102, 102, 255));

        lblFaseVentana.setText("Fase");

        lblNombreVentana.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        lblTipoVentana.setText("Mounstro");

        lblPvidaVentana.setText("PV");

        lblAtqVentana.setText("ATQ");

        lblEnergiaVentana.setText("Energía");

        lblHabilidadVentana.setText("Habilidad");

        lblCosteVentana.setText("Coste de Retirada");

        javax.swing.GroupLayout panelVentanaLayout = new javax.swing.GroupLayout(panelVentana);
        panelVentana.setLayout(panelVentanaLayout);
        panelVentanaLayout.setHorizontalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCosteVentana)
                    .addComponent(lblHabilidadVentana)
                    .addGroup(panelVentanaLayout.createSequentialGroup()
                        .addComponent(lblAtqVentana)
                        .addGap(42, 42, 42)
                        .addComponent(lblEnergiaVentana))
                    .addComponent(lblNombreVentana)
                    .addGroup(panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelVentanaLayout.createSequentialGroup()
                            .addComponent(lblFaseVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTipoVentana)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPvidaVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelVentanaLayout.setVerticalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaseVentana)
                    .addComponent(lblTipoVentana)
                    .addComponent(lblPvidaVentana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtqVentana)
                    .addComponent(lblEnergiaVentana))
                .addGap(37, 37, 37)
                .addComponent(lblHabilidadVentana)
                .addGap(18, 18, 18)
                .addComponent(lblCosteVentana)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnGuardarCartta.setText("Guardar");
        btnGuardarCartta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCarttaActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditorLayout = new javax.swing.GroupLayout(panelEditor);
        panelEditor.setLayout(panelEditorLayout);
        panelEditorLayout.setHorizontalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditorLayout.createSequentialGroup()
                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditorLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(spinerPV, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblHabilidadesAtaque)
                            .addGroup(panelEditorLayout.createSequentialGroup()
                                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblAccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblHabilidad, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(boxHabilidad, javax.swing.GroupLayout.Alignment.LEADING, 0, 66, Short.MAX_VALUE))
                                    .addComponent(spinnerAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblAtq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spinnerAtq)
                                        .addComponent(lblCostoRetirada))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubTipoCarta)
                            .addGroup(panelEditorLayout.createSequentialGroup()
                                .addComponent(lblNombreCarta)
                                .addGap(41, 41, 41)
                                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelEditorLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boxFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelEditorLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(lblFase))))))
                            .addComponent(boxSubTipoC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addGap(36, 36, 36)
                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditorLayout.createSequentialGroup()
                        .addComponent(btnGuardarCartta)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar))
                    .addComponent(panelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelEditorLayout.setVerticalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEditorLayout.createSequentialGroup()
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCarta)
                            .addComponent(txtNombreCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSubTipoCarta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxSubTipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPV)
                            .addComponent(lblFase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinerPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblHabilidadesAtaque)
                        .addGap(36, 36, 36)
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHabilidad)
                            .addComponent(lblAtq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxHabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerAtq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccion)
                            .addComponent(lblCostoRetirada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCartta)
                    .addComponent(btnRegresar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new EditorDeMazo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNombreCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCartaActionPerformed

    private void btnGuardarCarttaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCarttaActionPerformed

        CartaMonstruo cartaMonstruo = new CartaMonstruo(txtNombreCarta.getText(), Elemento.FUEGO.name(), PROPERTIES, NORMAL, "PROPERTIES", 1);
        try {
            AdministradorCartas.guardarCarta(cartaMonstruo);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_btnGuardarCarttaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxFase;
    private javax.swing.JComboBox<String> boxHabilidad;
    private javax.swing.JComboBox<String> boxSubTipoC;
    private javax.swing.JButton btnGuardarCartta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblAtq;
    private javax.swing.JLabel lblAtqVentana;
    private javax.swing.JLabel lblCosteVentana;
    private javax.swing.JLabel lblCostoRetirada;
    private javax.swing.JLabel lblEnergiaVentana;
    private javax.swing.JLabel lblFase;
    private javax.swing.JLabel lblFaseVentana;
    private javax.swing.JLabel lblHabilidad;
    private javax.swing.JLabel lblHabilidadVentana;
    private javax.swing.JLabel lblHabilidadesAtaque;
    private javax.swing.JLabel lblNombreCarta;
    private javax.swing.JLabel lblNombreVentana;
    private javax.swing.JLabel lblPV;
    private javax.swing.JLabel lblPvidaVentana;
    private javax.swing.JLabel lblSubTipoCarta;
    private javax.swing.JLabel lblTipoVentana;
    private javax.swing.JPanel panelEditor;
    private javax.swing.JPanel panelVentana;
    private javax.swing.JSpinner spinerPV;
    private javax.swing.JSpinner spinnerAccion;
    private javax.swing.JSpinner spinnerAtq;
    private javax.swing.JSpinner spinnerRetirada;
    private javax.swing.JTextField txtNombreCarta;
    // End of variables declaration//GEN-END:variables
}
