/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.segundoproyecto.frontend;

import com.mycompany.segundoproyecto.Juego;
import com.mycompany.segundoproyecto.jugador.Cpu;
import com.mycompany.segundoproyecto.jugador.CpuLista;
import com.mycompany.segundoproyecto.jugador.CpuTonta;
import com.mycompany.segundoproyecto.jugador.JugadorHumano;

/**
 *
 * @author fer
 */
public class Jugador extends javax.swing.JFrame {

    public Jugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jugdor = new javax.swing.JPanel();
        lblIngresaNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombreJugador = new javax.swing.JTextPane();
        lblOponente = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        comboBoxOponente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jugdor.setBackground(new java.awt.Color(102, 102, 255));

        lblIngresaNombre.setText("Ingresa tu nombre");

        jScrollPane1.setViewportView(txtNombreJugador);

        lblOponente.setText("Selecciona un oponente ");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        comboBoxOponente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ia Tonta", "Ia Lista" }));
        comboBoxOponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxOponenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JugdorLayout = new javax.swing.GroupLayout(Jugdor);
        Jugdor.setLayout(JugdorLayout);
        JugdorLayout.setHorizontalGroup(
            JugdorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JugdorLayout.createSequentialGroup()
                .addGroup(JugdorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JugdorLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(JugdorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngresaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(JugdorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JugdorLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnSiguiente)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        JugdorLayout.setVerticalGroup(
            JugdorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JugdorLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(JugdorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIngresaNombre)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(JugdorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOponente)
                    .addComponent(comboBoxOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnSiguiente)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jugdor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jugdor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

       
        JugadorHumano jugadorHumano = new JugadorHumano(txtNombreJugador.getText());
        
        Cpu cpu = null;
        
        if (comboBoxOponente.getSelectedIndex() == 0) {
            cpu = new CpuTonta();
        } else {
           cpu = new CpuLista();
        }
        
        Juego juego = new Juego(jugadorHumano ,cpu);
        
        
        //entra a la siguiente ventana 
        MenuSecundario menuSecundario = new MenuSecundario();
       menuSecundario.setJuego(juego);
       menuSecundario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed

  
    private void comboBoxOponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxOponenteActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_comboBoxOponenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jugdor;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> comboBoxOponente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIngresaNombre;
    private javax.swing.JLabel lblOponente;
    private javax.swing.JTextPane txtNombreJugador;
    // End of variables declaration//GEN-END:variables
}
